ServerEvents.recipes(e => {
    e.recipes.createMechanicalExtruderExtruding('minecraft:andesite', ['minecraft:water', 'minecraft:lava']).withCatalyst('uc:double_compressed_andesite')
    e.recipes.createMechanicalExtruderExtruding('minecraft:andesite', ['minecraft:water', 'kubejs:melted_andesite'])
    e.recipes.createMechanicalExtruderExtruding('minecraft:granite', ['minecraft:water', 'minecraft:lava']).withCatalyst('uc:double_compressed_granite')
    e.recipes.createMechanicalExtruderExtruding('minecraft:granite', ['minecraft:water', 'kubejs:melted_granite'])
    e.recipes.createMechanicalExtruderExtruding('minecraft:diorite', ['minecraft:water', 'minecraft:lava']).withCatalyst('uc:double_compressed_diorite')
    e.recipes.createMechanicalExtruderExtruding('minecraft:diorite', ['minecraft:water', 'kubejs:melted_diorite'])
    e.recipes.createMechanicalExtruderExtruding('minecraft:tuff', ['minecraft:water', 'minecraft:lava']).withCatalyst('uc:double_compressed_tuff')
    e.recipes.createMechanicalExtruderExtruding('minecraft:tuff', ['minecraft:water', 'kubejs:melted_tuff'])
    e.recipes.createMechanicalExtruderExtruding('minecraft:calcite', ['minecraft:water', 'minecraft:lava']).withCatalyst('uc:double_compressed_calcite')
    e.recipes.createMechanicalExtruderExtruding('minecraft:calcite', ['minecraft:water', 'kubejs:melted_calcite'])
})