#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 03 11:28:26 CST 2026
allowUnknownShaders=false
colorSpace=DISPLAY_P3
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.7.1 + EuphoriaPatches_1.8.6
